name: finkost
description: Aplikasi manajemen keuangan pribadi untuk gaya hidup modern.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Versi stabil terbaru
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # Isar (Database Lokal) - Versi stabil terbaru
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # State Management & Utilities
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  flutter_localizations: 
    sdk: flutter   
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: "^2.3.1"

  # Build Runners - Versi stabil terbaru
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1

# Konfigurasi khusus untuk build_runner (Isar)
builders:
  isar_generator:
    options:
      use_json_for_web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

# Bagian ini ditambahkan di paling bawah pubspec.yaml
flutter_launcher_icons:
  android: "launcher_icon" # Nama aset untuk Android
  ios: true                # Aktifkan untuk iOS
  image_path: "assets/images/app_icon.png" # Ganti dengan path logo Anda
  # optional: you can specify a custom image path for android or ios if needed
  # image_path_android: "assets/android.png"
  # image_path_ios: "assets/ios.png"
  # adaptive_icon_background: "#FFFFFF" # Warna latar belakang untuk Adaptive Icons (Android 8.0+)
  # adaptive_icon_foreground: "assets/foreground.png" # Gambar foreground untuk Adaptive Icons (Android 8.0+)

flutter_native_splash:
  color: "#B7A9D8"