name: finkost
description: Aplikasi manajemen keuangan pribadi untuk gaya hidup modern.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase - Versi stabil terbaru
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8

  # HIVE (Database Lokal) - Pengganti Isar
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State Management & Utilities
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.4
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.0
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  uuid: ^4.2.1
  dartz: ^0.10.1
  fl_chart: ^0.66.2
  path_provider: ^2.1.2
  pdf: ^3.11.1
  open_filex: ^4.5.0
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # Generator & Build Runner
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  
  # UI Assets Generators
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

# Konfigurasi Launcher Icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

# Konfigurasi Native Splash
flutter_native_splash:
  color: "#B7A9D8"
  # image: assets/images/splash.png # Tambahkan jika ada gambar splash